# Generated by Django 3.2.8 on 2021-12-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0016_rename_kyc_kycs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
