# Generated by Django 3.2.8 on 2021-12-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0029_auto_20211221_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_request',
            name='withdrew_from',
            field=models.CharField(default='choose', max_length=300),
        ),
    ]
