# Generated by Django 3.2.8 on 2021-11-09 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crpyto', '0002_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.ImageField(blank=True, null=True, upload_to='prof')),
                ('currency', models.CharField(max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=400)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
