# Generated by Django 3.2.8 on 2021-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0004_alter_deposit_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_history',
            name='status',
            field=models.BooleanField(choices=[('awaiting', 'Awaiting'), ('declind', 'Declind'), ('confirmed', 'Confirmed')], default='awaiting'),
        ),
    ]
