# Generated by Django 3.2.8 on 2021-11-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0005_alter_deposit_history_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit_history',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('declind', 'Declind'), ('confirmed', 'Confirmed')], default='awaiting', max_length=400),
        ),
    ]
