# Generated by Django 3.2.8 on 2021-11-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0008_alter_withdraw_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_request',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdraw_request',
            name='status',
            field=models.CharField(choices=[('awaiting', 'Awaiting'), ('declind', 'Declind'), ('confirmed', 'Confirmed')], default='awaiting', max_length=400),
        ),
    ]
