# Generated by Django 3.2.8 on 2021-11-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0013_auto_20211113_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='balance',
        ),
    ]
