# Generated by Django 4.0 on 2021-12-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crpyto', '0014_remove_userwallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration_period',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='appruved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='item_created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='roi',
            field=models.CharField(default='8%', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermembership',
            name='statuse',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=30),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdraw_request',
            name='withdrew_from',
            field=models.CharField(default='choose', max_length=300),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Elite', 'Elite'), ('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Basic', 'Basic')], default='Basic', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_membership', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='bonus',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='deposited',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='profit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='ref_bonus',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='kycs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=300)),
                ('id_front', models.ImageField(upload_to='national_id/images')),
                ('id_back', models.ImageField(upload_to='national_id/images')),
                ('id_body', models.ImageField(upload_to='national_id/images')),
                ('id_number', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('declind', 'Declind'), ('confirmed', 'Confirmed')], default='awaiting', max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
