# Generated by Django 4.0 on 2022-08-23 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crpyto', '0016_deposit_history_created_dated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_dated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
